name: Update datos diarios

on:
  schedule:
    - cron: "0 12 * * *" # todos los d√≠as 07:00 Ecuador (UTC-5)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Where am I?
        run: pwd
        
      - name: Show repo files
        run: ls -R

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests

      - name: Run extraction script
        run: python "${{ github.workspace }}/scripts/extraccionDatos.py"

      - name: Commit updated JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/datos_latest.json
          git commit -m "Auto update datos_latest.json" || echo "No changes"
          git push
